name: harry_potter_app
description: A Harry Potter themed Flutter application.
version: 1.0.0

environment:
  sdk: '^3.4.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  image_picker: ^0.8.4
  provider: ^5.0.0

  equatable: ^2.0.3
  shared_preferences: ^2.0.8
  path_provider: ^2.0.2

  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/search.png
  fonts:
    - family: HarryP
      fonts:
        - asset: assets/HarryP.TTF
